apiVersion: v1
kind: Pod
metadata:
  name: nginx  #name of the Pod
  labels:
   app: nginx  # use this label to expose on service
spec:
  containers:
  - name: nginx  # name of the container
    image: nginx:1.14.2
    ports:
    - containerPort: 80


